movie_review/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_review/movie_review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
]

movie_review/review/urls.py
from django.urls import path
from . import views

app_name='review'

urlpatterns = [
    path('', views.review_list, name="list"),
    path('<int:pk>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('<int:pk>/update/', views.review_update, name="update"),
    path('<int:pk>/delete/', views.review_delete, name="delete"),
    path("ex", views.ex),

]

movie_review/review/models.py
from django.db import models

# Create your models here.

class Director(models.Model):
    name = models.CharField(max_length=30)
    age = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Actor(models.Model):
    name = models.CharField(max_length=30)
    age = models.CharField(max_length=30)

    def __str__(self):
        return self.name


GENRE_CHOICES= (('SF', 'SF'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'))
class Review(models.Model):
    title = models.CharField(max_length=30)
    release_date = models.IntegerField(default=1990)#개봉년도
    genre = models.CharField(max_length=50, choices=GENRE_CHOICES)
    rating = models.FloatField(default=0)#별점
    running_time = models.IntegerField(null=True, blank=True)
    content = models.TextField()#리뷰내용
    # director = models.CharField(max_length=20)
    # actor = models.CharField(max_length=255)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    actor = models.ManyToManyField(Actor, blank=True)
    image = models.ImageField(upload_to="poster", null=True, blank=True)

    def __str__(self):
        return self.title

movie_review/review/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review, Director, Actor
from .form import ReviewForm
# Create your views here.
from django.db.models import Q
from django.http import HttpResponse



def review_list(request):
    reviews = Review.objects.all()
    # print("reviews:", type(reviews))


    # print("reviews.title:",reviews.title)

    # for r in Review.objects.all():
    #     print("r type:", type(r))
    #     s = str(r.id) + ' : ' + r.title + '\n'
    #     print(s)

    # row = Review.objects.get(title="스파이더맨: 노 웨이 홈") # pk는 모델에서 변수로 추가 안해도 생성되는 거 다들 아시죠?
    # print(row.title)
    # print(type(row))#찍히는 객체의 타입도 확인을 해보자.

    reviews = Review.objects.all()
    print("reviews:", reviews)
    # rows = Review.objects.filter(Q(title='스파이더맨') | Q(release_date="2016"))

    # rows = Review.objects.exclude(title='스파이더맨')
    # print("rows:", rows)
    # c = Review.objects.exclude(title='스파이더맨').count()
    # print("c:", c)
    rows = Review.objects.order_by('?').first()
    print("rows type:", type(rows))
    # for r in rows:
    #     print("r id:", r.id, ", r title: ", r.title)


    ctx = {'reviews': reviews}

    return render(request, template_name='movie_list.html', context=ctx)

def ex(request):
    print("ex enter")
    response = HttpResponse("<div>Hello World!</div>")
    return response


def detail(request, pk):
    review = Review.objects.get(id=pk)
    hour = 0
    minute = 0
    if int(review.running_time) > 60:
        hour = int(review.running_time) // 60
        minute = int(review.running_time) % 60
    print("hour:", hour)
    print("minute:", minute)
    print("review.running_time:", review.running_time)

    print("director:", review.director)

    dir = Director.objects.get(name="존 왓츠")
    print("dir:", dir)
    print("director2.review_set.all():", dir.review_set.all())


    actor = Actor.objects.get(pk=1)
    print("actors:", actor)
    print("actors set all:", actor.review_set.all())

    print("review.all", review.actor.all())
    actors = review.actor.all()

    ctx = {'review': review, 'hour': hour, 'minute': minute, "actors":actors}

    return render(request, template_name='movie_detail.html', context=ctx)


def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save()
            return redirect("review:list")
    else:
        print("here!")
        print(request.method)
        print("request.GET:", request.GET)
        form = ReviewForm()
        print()
        ctx = {'form': form}

        return render(request, template_name='movie_form.html', context=ctx)


def review_update(request, pk):
    review = get_object_or_404(Review, id=pk)

    if request.method == 'POST':
        print("request method:", request.method)
        form = ReviewForm(request.POST, instance=review)
        # print("form:", form)
        print("request.POST:", request.POST) #request.POST로 들어오는 것 전부 출력!
        print("request.FILES:", request.FILES)
        review.title = request.POST.get("title")
        review.release_date = request.POST.get("release_date")
        review.genre = request.POST.get("genre")
        review.rating = request.POST.get("rating")
        review.running_time = request.POST.get("running_time")
        review.content = request.POST.get("content")

        get_dir_name = request.POST.get("director")
        direc = Director.objects.get(name=get_dir_name)
        review.director = direc

        get_act_name = request.POST.get("actor")
        act = Actor.objects.get(name=get_act_name)
        review.actor.add(act)#manyto many field save

        poster = request.FILES.get('poster')
        review.image = poster
        review.save()
        return redirect('review:detail', pk)

        # if form.is_valid():
        #     print("form valid")
        #     review = form.save()
        #     return redirect('review:detail', pk)
        # else:
        #     print("no valid")

    else:
        form = ReviewForm(instance=review)
        ctx = {'form': form, 'review': review}

        return render(request, template_name='movie_form.html', context=ctx)


def review_delete(request, pk):
    review = Review.objects.get(id=pk)
    review.delete()
    return redirect('review:list')
    # return render(request, template_name='movie_list.html', context=ctx)

movie_review/review/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
    <title>My Movie reviews</title>
</head>
<body>
    <header>
        <h1><a href="/review">My Movie reviews</a></h1>
        <a href="{% url 'review:create' %}"><span class="">Post a new review</span></a>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

movie_review/review/templates/movie_create_add.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Review</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

movie_review/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?after"> 
    <title>My Movie reviews</title>
    <p>static path: {% static 'css/style.css' %}</p>
</head>
<body>
    <header>
        <h1 class="header-title"><a href="/review/">my <span class="highlight">Movie</span> reviews</a></h1>
        <a href="{% url 'review:create' %}"><span class="header-new">Add a New review</span></a>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

movie_review/templates/movie_detail.html
{% extends "base.html" %}

{% block content %}

<div class="detail">
    <div class="detail-top">
        <h1 class="detail-title">{{ review.title }}</h1>
        <div>
            <a href="{% url 'review:update' review.id %}"><span class="detail-ud">수정</span></a>
            <a href="{% url 'review:delete' review.id %}"><span class="detail-ud">삭제</span></a>
        </div>
    </div>
    <div class="detail-info">
        <div class=list-poster>
            {% if review.image %}
                <img src="{{review.image.url}}" height="220" width="160">
            {% else %}
                <img src="https://picsum.photos/seed/{{review.id}}/160/220?">
            {% endif %}
        </div>
        
        <div class="detail-review1">
            <p><span class="detail-item">개봉년도</span> <span class="detail-content">  {{ review.release_date }}년</span></p>
            <p><span class="detail-item">감독</span> <span class="detail-content">  {{ review.director }}</span></p>
            <p><span class="detail-item">주연</span> <span class="detail-content">  
                {% for actor in actors %}
                {{actor.name}}
                {% endfor %}
            </span></p>
            <p><span class="detail-item">장르</span> <span class="detail-content">  {{ review.genre }}</span></p>
            <p><span class="detail-item">별점</span> <span class="detail-content">  {{ review.rating }}</span></p>
            <p><span class="detail-item">러닝타임</span> <span class="detail-content">  
                {% if hour %}
                    {{ hour }}시간 {{ minute }} 분
                {% else %}
                    {{ review.running_time }} 분
                {% endif %}
            </span></p>
        </div>
    </div>
    <div class="detail-review2">
        <p id="review">{{ review.content }}</p>
    </div>
</div>
{% endblock %}

movie_review/templates/movie_form.html
{% extends 'base.html' %}

{% block content %}
<div class="form-container">
    <div class="form">
        <h2 class="form-title">  <span class="highlight">Movie</span> review 🍿</h2>
        <hr/>
        <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                <label>제목: </label> 
                <input class="form-input" name="title" type="text" maxlength="30" value="{% if review.title %}{{review.title}}{% endif %}">
            </p>
            <p>
                <label>개봉년도: </label> 
                <input id="release-date" class="form-input" name="release_date" type="number" value="{% if review.release_date %}{{review.release_date}}{% endif %}">
            </p>
            <p>
                <label>장르: </label> 
                <span>{{form.genre}}</span>
            </p>
            <p>
                <label>별점: </label> 
                <input id="rating" class="form-input" name="rating" type="number" step="0.01" value="{% if review.rating %}{{review.rating}}{% endif %}" step="0.1" >
            </p>
            <p>
                <label>러닝타임: </label>
                <input id="running-time" class="form-input" type="text" maxlength="10" name="running_time" value="{% if review.running_time %}{{review.running_time}}{% endif %}">
            </p>
            <p>
                <p id="review-content"><label>리뷰: </label></p>
                <textarea class="content-input" cols="63" rows="10" name="content">{% if review.content %}{{review.content}}{% endif %}</textarea>
            </p>
            <p>
                <label>감독: </label> 
                <input class="form-input" name="director" type="text" maxlength="20" value="{% if review.director%}{{review.director}}{% endif %}">
            </p>
            <p>
                <label>배우: </label> 
                <input class="form-input" name="actor" type="text" maxlength="255" value="{% if review.actor %}{{review.actor}}{% endif %}">
            </p>
            <p>
                <label>사진: </label> 
                <input class="form-input" name="poster" type="file" maxlength="255" value="{% if review.image %}{{review.image.url}}{% endif %}">
            </p>
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
</div>
{% endblock %}

movie_review/templates/movie_list.html
{% extends "base.html" %}

{% block content %}
<div class="list-reviews"> 
    {%for review in reviews %}
    <div class="list-review">
        <div class=list-poster>
            {% if review.image %}
                <img src="{{review.image.url}}" height="220" width="160">
            {% else %}
                <img src="https://picsum.photos/seed/{{review.id}}/160/220?">
            {% endif %}
        </div>
        <a href="{% url 'review:detail' review.id %}"><h2>{{ review.title }}</h2></a>
        <p><span class="list-item">개봉년도</span>   <span class="list-content">{{ review.release_date }}년</span></p>
        <p><span class="list-item">장르</span>   <span class="list-content">{{ review.genre }}</span></p>
        <p><span class="list-item">별점</span>   <span class="list-content">{{ review.rating }}</span></p>
    </div>
    {% endfor %}
</div>
{% endblock %}